name: .NET

on:
  push:
    branches: [ develop ]

  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-preview.1.21103.13

    - name: Restore ReaLTaiizor
      run: dotnet restore src
    - name: Build ReaLTaiizor
      run: dotnet build src --no-restore /nowarn:CS0109,CS0414,CA1416
    - name: Test ReaLTaiizor
      run: dotnet test src --no-build --verbosity normal

    - name: Restore ReaLTaiizor.Defender
      run: dotnet restore sample/ReaLTaiizor.Defender
    - name: Build ReaLTaiizor.Defender
      run: dotnet build sample/ReaLTaiizor.Defender --no-restore
    - name: Test ReaLTaiizor.Defender
      run: dotnet test sample/ReaLTaiizor.Defender --no-build --verbosity normal

    - name: Restore ReaLTaiizor.Instagram
      run: dotnet restore sample/ReaLTaiizor.Instagram
    - name: Build ReaLTaiizor.Instagram
      run: dotnet build sample/ReaLTaiizor.Instagram --no-restore
    - name: Test ReaLTaiizor.Instagram
      run: dotnet test sample/ReaLTaiizor.Instagram --no-build --verbosity normal

    - name: Restore ReaLTaiizor.Kaspersky
      run: dotnet restore sample/ReaLTaiizor.Kaspersky
    - name: Build ReaLTaiizor.Kaspersky
      run: dotnet build sample/ReaLTaiizor.Kaspersky --no-restore
    - name: Test ReaLTaiizor.Kaspersky
      run: dotnet test sample/ReaLTaiizor.Kaspersky --no-build --verbosity normal

    - name: Restore ReaLTaiizor.Login
      run: dotnet restore sample/ReaLTaiizor.Login
    - name: Build ReaLTaiizor.Login
      run: dotnet build sample/ReaLTaiizor.Login --no-restore
    - name: Test ReaLTaiizor.Login
      run: dotnet test sample/ReaLTaiizor.Login --no-build --verbosity normal

    - name: Restore ReaLTaiizor.Payment
      run: dotnet restore sample/ReaLTaiizor.Payment
    - name: Build ReaLTaiizor.Payment
      run: dotnet build sample/ReaLTaiizor.Payment --no-restore
    - name: Test ReaLTaiizor.Payment
      run: dotnet test sample/ReaLTaiizor.Payment --no-build --verbosity normal

    - name: Restore ReaLTaiizor.Player
      run: dotnet restore sample/ReaLTaiizor.Player
    - name: Build ReaLTaiizor.Player
      run: dotnet build sample/ReaLTaiizor.Player --no-restore
    - name: Test ReaLTaiizor.Player
      run: dotnet test sample/ReaLTaiizor.Player --no-build --verbosity normal

    - name: Restore ReaLTaiizor.Rufus
      run: dotnet restore sample/ReaLTaiizor.Rufus
    - name: Build ReaLTaiizor.Rufus
      run: dotnet build sample/ReaLTaiizor.Rufus --no-restore
    - name: Test ReaLTaiizor.Rufus
      run: dotnet test sample/ReaLTaiizor.Rufus --no-build --verbosity normal

    - name: Restore ReaLTaiizor.XAMPP
      run: dotnet restore sample/ReaLTaiizor.XAMPP
    - name: Build ReaLTaiizor.XAMPP
      run: dotnet build sample/ReaLTaiizor.XAMPP --no-restore
    - name: Test ReaLTaiizor.XAMPP
      run: dotnet test sample/ReaLTaiizor.XAMPP --no-build --verbosity normal

    - name: Restore ReaLTaiizor.AppLocker
      run: dotnet restore ready/ReaLTaiizor.AppLocker
    - name: Build ReaLTaiizor.AppLocker
      run: dotnet build ready/ReaLTaiizor.AppLocker --no-restore
    - name: Test ReaLTaiizor.AppLocker
      run: dotnet test ready/ReaLTaiizor.AppLocker --no-build --verbosity normal

    - name: Restore ReaLTaiizor.Translate
      run: dotnet restore ready/ReaLTaiizor.Translate
    - name: Build ReaLTaiizor.Translate
      run: dotnet build ready/ReaLTaiizor.Translate --no-restore
    - name: Test ReaLTaiizor.Translate
      run: dotnet test ready/ReaLTaiizor.Translate --no-build --verbosity normal

    - name: Restore ReaLTaiizor.UI
      run: dotnet restore demo/ReaLTaiizor.UI
    - name: Build ReaLTaiizor.UI
      run: dotnet build demo/ReaLTaiizor.UI --no-restore
    - name: Test ReaLTaiizor.UI
      run: dotnet test demo/ReaLTaiizor.UI --no-build --verbosity normal

    - name: Restore ReaLTaiizor.UX
      run: dotnet restore demo/ReaLTaiizor.UX
    - name: Build ReaLTaiizor.UX
      run: dotnet build demo/ReaLTaiizor.UX --no-restore
    - name: Test ReaLTaiizor.UX
      run: dotnet test demo/ReaLTaiizor.UX --no-build --verbosity normal