name: .NET

on:
  push:
    branches: [ develop ]

  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x-preview

    - name: Restore ReaLTaiizor
      run: dotnet restore src
    - name: Build ReaLTaiizor
      run: dotnet build src --no-restore
    - name: Test ReaLTaiizor
      run: dotnet test src --no-build --verbosity normal